image: pikalab/ci:ubuntu-jdk14-git-gradle-graphviz

before_script:
  - chmod +x gradlew
  - source $HOME/.sdkman/bin/sdkman-init.sh

cache:
  paths:
    - $HOME/.gradle/
    - gradle/
    - .gradle/
    - build/

variables:
  GOPTS: "--no-daemon --console=plain"
  ORG_GRADLE_PROJECT_orchidBaseUrl: "https://pika-lab.gitlab.io/argumentation/arg2p/"

build:
  stage: build
  script: ./gradlew classes javadoc $GOPTS

test:
  stage: test
  script: ./gradlew check $GOPTS

pages:
  script:
    - mkdir public
    - ./gradlew orchidBuild $GOPTS
    - cp -r doc/build/docs/orchid/* public
  artifacts:
    paths:
      - public
  only:
    - /^(master)|(release)|(documentation)$/
