image: pikalab/ci:ubuntu-jdk14-git-gradle-graphviz

before_script:
  - chmod +x gradlew
  - source $HOME/.sdkman/bin/sdkman-init.sh

cache:
  paths:
    - $HOME/.gradle/
    - gradle/
    - .gradle/
    - build/

variables:
  GOPTS: "--no-daemon --console=plain"

build:
  stage: build
  script: ./gradlew classes javadoc $GOPTS

test:
  stage: test
  script: ./gradlew check $GOPTS
