image: pikalab/ci:ubuntu-jdk14-git-gradle-graphviz

stages:
  - build
  - test
  - post

before_script:
  - chmod +x gradlew
  - source $HOME/.sdkman/bin/sdkman-init.sh

cache:
  paths:
    - $HOME/.gradle/
    - gradle/
    - .gradle/
    - build/

variables:
  GOPTS: "--no-daemon --console=plain"
  ORG_GRADLE_PROJECT_orchidBaseUrl: "https://pika-lab.gitlab.io/argumentation/arg2p/"
  GCMD: gradle

build:
  stage: build
  script: $GCMD classes javadoc $GOPTS

test:
  stage: test
  script: $GCMD check $GOPTS

pages:
  script:
    - mkdir public
    - $GCMD orchidBuild $GOPTS
    - cp -r doc/build/docs/orchid/* public
  artifacts:
    paths:
      - public
  only:
    - /^(master)|(release)|(documentation)$/

build:create-jar:
  only:
    - master
  before_script: []
  script:
    - $GCMD :arg2p:shadowJar
  artifacts:
    paths:
      - ./arg2p/build/libs/*.jar

#build:create-osx-executable:
#  only:
#    - master
#  before_script: []
#  script:
#    - $GCMD :arg2p:jpackage
#  artifacts:
#    paths:
#      - ./arg2p/build/jpackage/*.dmg

build:create-deb-executable:
  image: pikalab/ci:ubuntu-jdk14-git-gradle-graphviz
  only:
    - master
  before_script: []
  script:
    - $GCMD :arg2p:jpackage
    artifacts:
      paths:
        - ./arg2p/build/jpackage/*.deb

#build:create-win-executable:
#  only:
#    - master
#  before_script: []
#  script:
#    - $GCMD :arg2p:shadowJar
#  artifacts:
#    paths:
#      - ./arg2p/build/libs/*.jar

#post:create:gitlab:release:
#  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-release
#  stage: post
#  only:
#    - master
#    - tags
#  before_script: []
#  script:
#    - gitlab_auto_release -c CHANGELOG.md -d "This was auto-generated by the gitlab-auto-release tool" --artifacts "build:create-jar"
