image: pikalab/ci:ubuntu-jdk14-git-gradle-graphviz

stages:
  - build
  - test
  - post

before_script:
  - chmod +x gradlew
  - source $HOME/.sdkman/bin/sdkman-init.sh

cache:
  paths:
    - $HOME/.gradle/
    - gradle/
    - .gradle/
    - build/

variables:
  GOPTS: "--no-daemon --console=plain"
  ORG_GRADLE_PROJECT_orchidBaseUrl: "https://pika-lab.gitlab.io/argumentation/arg2p/"
  GCMD: gradle
  VERSION: v0.3.2

build:
  stage: build
  script: $GCMD classes javadoc $GOPTS

test:
  stage: test
  script: $GCMD check $GOPTS

pages:
  script:
    - mkdir public
    - $GCMD orchidBuild $GOPTS
    - cp -r doc/build/docs/orchid/* public
  artifacts:
    paths:
      - public
  only:
    - /^(master)|(release)|(documentation)$/

post:create:gitlab:release:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-release
  stage: post
  before_script: []
  script:
    - gitlab_auto_release --tag-name $VERSION --release-name $VERSION --changelog CHANGELOG.md --description "This was auto-generated by the gitlab-auto-release tool" --asset "arg2p.jar=https://github.com/tuProlog/arg2p/releases/download/${VERSION}/arg2p.jar" --asset "arg2p-osx.dmg=https://github.com/tuProlog/arg2p/releases/download/${VERSION}/arg2p-osx.dmg" --asset "arg2p-lin.deb=https://github.com/tuProlog/arg2p/releases/download/${VERSION}/arg2p-lin.deb" --asset "arg2p-win.msi=https://github.com/tuProlog/arg2p/releases/download/${VERSION}/arg2p-win.msi"
